services:
  - type: web
    name: femospace-backend
    env: node
    buildCommand: npm install && npm run build --workspace=backend
    startCommand: npm run start:prod --workspace=backend
    envVars:
      - key: NODE_ENV
        value: production
