export const COUNTRIES = [
  { code: '+1', name: 'United States' },
  { code: '+1', name: 'Canada' },
  { code: '+44', name: 'United Kingdom' },
  { code: '+61', name: 'Australia' },
  { code: '+91', name: 'India' },
  { code: '+86', name: 'China' },
  { code: '+81', name: 'Japan' },
  { code: '+82', name: 'South Korea' },
  { code: '+33', name: 'France' },
  { code: '+49', name: 'Germany' },
  { code: '+39', name: 'Italy' },
  { code: '+34', name: 'Spain' },
  { code: '+31', name: 'Netherlands' },
  { code: '+43', name: 'Austria' },
  { code: '+41', name: 'Switzerland' },
  { code: '+46', name: 'Sweden' },
  { code: '+47', name: 'Norway' },
  { code: '+45', name: 'Denmark' },
  { code: '+358', name: 'Finland' },
  { code: '+32', name: 'Belgium' },
  { code: '+27', name: 'South Africa' },
  { code: '+55', name: 'Brazil' },
  { code: '+54', name: 'Argentina' },
  { code: '+56', name: 'Chile' },
  { code: '+57', name: 'Colombia' },
  { code: '+52', name: 'Mexico' },
  { code: '+64', name: 'New Zealand' },
  { code: '+65', name: 'Singapore' },
  { code: '+60', name: 'Malaysia' },
  { code: '+62', name: 'Indonesia' },
  { code: '+63', name: 'Philippines' },
  { code: '+66', name: 'Thailand' },
  { code: '+84', name: 'Vietnam' },
  { code: '+880', name: 'Bangladesh' },
  { code: '+92', name: 'Pakistan' },
  { code: '+971', name: 'United Arab Emirates' },
  { code: '+966', name: 'Saudi Arabia' },
  { code: '+20', name: 'Egypt' },
  { code: '+212', name: 'Morocco' },
  { code: '+216', name: 'Tunisia' },
  { code: '+234', name: 'Nigeria' },
  { code: '+212', name: 'Algeria' },
  { code: '+90', name: 'Turkey' },
  { code: '+48', name: 'Poland' },
  { code: '+40', name: 'Romania' },
  { code: '+359', name: 'Bulgaria' },
  { code: '+30', name: 'Greece' },
  { code: '+385', name: 'Croatia' },
  { code: '+36', name: 'Hungary' },
  { code: '+420', name: 'Czech Republic' },
  { code: '+421', name: 'Slovakia' },
  { code: '+43', name: 'Austria' },
  { code: '+351', name: 'Portugal' },
  { code: '+38', name: 'Ukraine' },
  { code: '+372', name: 'Estonia' },
  { code: '+371', name: 'Latvia' },
  { code: '+370', name: 'Lithuania' },
  { code: '+389', name: 'North Macedonia' },
  { code: '+382', name: 'Montenegro' },
  { code: '+387', name: 'Bosnia and Herzegovina' },
  { code: '+383', name: 'Kosovo' },
  { code: '+355', name: 'Albania' },
  { code: '+95', name: 'Myanmar' },
  { code: '+855', name: 'Cambodia' },
  { code: '+856', name: 'Laos' },
  { code: '+886', name: 'Taiwan' },
  { code: '+852', name: 'Hong Kong' },
  { code: '+853', name: 'Macau' },
  { code: '+886', name: 'Taiwan' },
  { code: '+852', name: 'Hong Kong' },
  { code: '+880', name: 'Bangladesh' },
];
